///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GitJenkins
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("b103ed0c-7eb5-43da-8978-320722ae1aec", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the GitJenkinsRepository repository.
        /// </summary>
        public static GitJenkinsRepository repo = GitJenkinsRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ayarlar.AramaKutusuBirAyarBul' at 154;17.", repo.Ayarlar.AramaKutusuBirAyarBulInfo, new RecordItemIndex(0));
            repo.Ayarlar.AramaKutusuBirAyarBul.Click("154;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ses' with focus on 'Ayarlar'.", repo.Ayarlar.SelfInfo, new RecordItemIndex(1));
            repo.Ayarlar.Self.EnsureVisible();
            Keyboard.Press("ses");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ayarlar.SearchAutoSuggestBox' at 89;88.", repo.Ayarlar.SearchAutoSuggestBoxInfo, new RecordItemIndex(2));
            repo.Ayarlar.SearchAutoSuggestBox.Click("89;88");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Ayarlar.HorizontalThumb' at 3;9.", repo.Ayarlar.HorizontalThumbInfo, new RecordItemIndex(3));
            repo.Ayarlar.HorizontalThumb.MoveTo("3;9");
            repo.Ayarlar.HorizontalThumb.MouseDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Ayarlar.HorizontalThumb' at 41;57.", repo.Ayarlar.HorizontalThumbInfo, new RecordItemIndex(4));
            repo.Ayarlar.HorizontalThumb.MoveTo("41;57");
            repo.Ayarlar.HorizontalThumb.MouseUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
